const promociones = [
  {
    id: 1,
    empresa: "Elektra",
    urlImg: "img/elektra.png",
    highLight: "5%",
    desc: "de descuento adicional",
    vigencia: "05/31/2022",
  },
  {
    id: 2,
    empresa: "VIPS",
    urlImg: "img/vips.png",
    highLight: "25%",
    desc: "descuento con Q07R0NPCC3",
    vigencia: "12/31/2022",
  },
  {
    id: 3,
    empresa: "KFC",
    urlImg: "img/kfc.png",
    highLight: "$233",
    desc: "en combo 10pz Crujipollo",
    vigencia: "07/18/2022",
  },
  {
    id: 4,
    empresa: "KFC",
    urlImg: "img/kfc.png",
    highLight: "$328",
    desc: "en combo 14pz Crujipollo",
    vigencia: "07/18/2022",
  },
  {
    id: 5,
    empresa: "KFC",
    urlImg: "img/kfc.png",
    highLight: "$83",
    desc: "en combo 3 Ke-tiras",
    vigencia: "07/18/2022",
  },
  {
    id: 6,
    empresa: "Chopo",
    urlImg: "img/chopo.png",
    highLight: "20%",
    desc: "en estudios de laboratorio",
    vigencia: "10/31/2022",
  },
  {
    id: 7,
    empresa: "Chopo",
    urlImg: "img/chopo.png",
    highLight: "15%",
    desc: "en estudios de gabinete",
    vigencia: "10/31/2022",
  },
  {
    id: 8,
    empresa: "Chopo",
    urlImg: "img/chopo.png",
    highLight: "5%",
    desc: "en estudios especiales",
    vigencia: "10/31/2022",
  },
  {
    id: 9,
    empresa: "Chopo",
    urlImg: "img/chopo.png",
    highLight: "3%",
    desc: "adicional a promos",
    vigencia: "10/31/2022",
  },
  {
    id: 10,
    empresa: "Óptica Americana",
    urlImg: "img/americana.png",
    highLight: "15%",
    desc: "en compra de anteojos",
    vigencia: "06/30/2022",
  },
  {
    id: 11,
    empresa: "Harmon Hall",
    urlImg: "img/harmanhall.png",
    highLight: "$500",
    desc: "máximo de descuento",
    vigencia: "06/30/2022",
  },
  {
    id: 12,
    empresa: "JULIO",
    urlImg: "img/julio.png",
    highLight: "10%",
    desc: "de descuento",
    vigencia: "12/31/2022",
  },
  {
    id: 13,
    empresa: "flexi",
    urlImg: "img/flexi.png",
    highLight: "10%",
    desc: "descuento en calzado",
    vigencia: "04/30/2022",
  },
  {
    id: 14,
    empresa: "Rinna Bruni",
    urlImg: "img/rb.png",
    highLight: "10%",
    desc: "de descuento",
    vigencia: "06/30/2022",
  },
  {
    id: 15,
    empresa: "¡Recórcholis!",
    urlImg: "img/recorcholis.png",
    highLight: "$150",
    desc: "adicionales al recargar",
    vigencia: "12/31/2022",
  },
  {
    id: 16,
    empresa: "COSTCO",
    urlImg: "img/costco.png",
    highLight: "$250",
    desc: "en monedero electrónico",
    vigencia: "04/30/2022",
  },
  {
    id: 17,
    empresa: "ClickBus",
    urlImg: "img/clickbus.png",
    highLight: "10%",
    desc: "de descuento",
    vigencia: "07/15/2022",
  },
  {
    id: 18,
    empresa: "Viajes Libertad",
    urlImg: "img/viajes.png",
    highLight: "10%",
    desc: "descuento en el total",
    vigencia: "10/31/2022",
  },
  {
    id: 19,
    empresa: "volaris",
    urlImg: "img/volaris.png",
    highLight: "55%",
    desc: "de descuento máximo",
    vigencia: "03/23/2022",
  },
];
